version: '3.6'

services:
  postgres:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database1
    ports:
      - 5432:5432